title: Naman Nigam's Blog
email: namannigam12@gmail.com
description: >-
  Blog about high and low level system designs.
baseurl: ""
url: "https://namannigam.github.io"

timezone: Asia/Kolkata
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-redirect-from

future: false
strict_front_matter: true

gist:
  noscript: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Naman Nigam
  tagline: |
    Software Developer,
    Flipkart, India
  date_format: "%b %-d, %Y"

  social_links:
    github: namannigam
    twitter: aBitOfNaman
    linkedIn: in/namannigam

  navigation:
    - title: Posts
      url: "/posts"
    - title: About
      url: "/about"

  sitemap: true

show_excerpts: true