title: Naman Nigam's Blog
email: namannigam12@gmail.com
description: >-
  Blog about high and low level system designs.
baseurl: "/"

timezone: Asia/Kolkata
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-default-layout

future: true
strict_front_matter: true

gist:
  noscript: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  portfolio_image: assets/dp.jpg
  name: Naman Nigam
  tagline: |
    Software Developer,
    Flipkart, India
  date_format: "%b %-d, %Y"

  social_links:
    twitter: aBitOfNaman
    github: namannigam
    linkedIn: in/namannigam

  navigation:
    - title: Posts
      url: "/posts"
    - title: Projects
      url: "/projects"
    - title: Pages
      url: "/pages"
    - title: About
      url: "/about"

  sitemap: true

show_excerpts: true