title: Articles
email: namannigam12@gmail.com
description: >-
  Posts around project experiences and learnings.
baseurl: ""
url: "https://namannigam.github.io"

timezone: Asia/Kolkata
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-redirect-from

future: false
strict_front_matter: true

gist:
  noscript: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

include: favicon.ico

remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  portfolio_image: "assets/portfolio.png"
  name: Naman Nigam
  tagline: |
    Software Developer,
    Flipkart, India
  date_format: "%b %-d, %Y"

  social_links:
    github: namannigam
    twitter: aBitOfNaman
    linkedIn: in/namannigam

  navigation:
    - title: Posts
      url: "/posts"
    - title: Projects
      url: "/projects"
    - title: About
      url: "/about"

  sitemap: true

  condensed_mobile:
    - home
    - post

  dark_mode: true

show_excerpts: true